parseInputOptions return missing
Hot-fix for VSCode 2019 build:

C:\projects\SimCenter\SimCenterCommon\Common\Utils\SimCenterConfigFile.cpp(94) : error C4716: 'parseInputOptions': must return a value